/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodRouteImport } from './routes/method'
import { Route as StudioStudyIdRouteImport } from './routes/studio.$studyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioStudyIdRoute = StudioStudyIdRouteImport.update({
  id: '/studio/$studyId',
  path: '/studio/$studyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/studio/$studyId': typeof StudioStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/studio/$studyId': typeof StudioStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/studio/$studyId': typeof StudioStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/method' | '/studio/$studyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/method' | '/studio/$studyId'
  id: '__root__' | '/' | '/method' | '/studio/$studyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodRoute: typeof MethodRoute
  StudioStudyIdRoute: typeof StudioStudyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$studyId': {
      id: '/studio/$studyId'
      path: '/studio/$studyId'
      fullPath: '/studio/$studyId'
      preLoaderRoute: typeof StudioStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodRoute: MethodRoute,
  StudioStudyIdRoute: StudioStudyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
